build: Improve error diagnosis for configure version fetching script
Check for git being present and error out otherwise explaining why. And
improve the fallback error message to mention that this is neither a git
checkout nor a distribution tarball.

Prompted-by: Norbert Preining <norbert@preining.info>

diff --git a/get-version b/get-version
--- a/get-version
+++ b/get-version
@@ -2,7 +2,7 @@
 #
 # get-version
 #
-# Copyright © 2009, 2013-2014 Guillem Jover <guillem@debian.org>
+# Copyright © 2009, 2013-2015, 2018, 2020 Guillem Jover <guillem@debian.org>
 #
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -18,10 +18,20 @@
 # along with this program.  If not, see <https://www.gnu.org/licenses/>.
 #
 
+error()
+{
+  echo "get-version: error: $*" 1>&2
+  exit 1
+}
+
 if [ -f .dist-version ]; then
   # Get the version from the file distributed in the tarball.
   version=$(cat .dist-version)
 elif [ -d .git ] || [ -f .git ]; then
+  if ! command -v git >/dev/null; then
+    error "cannot get project version, git checkout but git program not found"
+  fi
+
   # Get the version from the git repository. Since tags cannot contain colons
   # or tildes, we use percent and underscore instead. Reverse that switch here.
   version=$(git describe --abbrev=4 HEAD 2>/dev/null | tr %_ :~)
@@ -33,8 +43,7 @@ elif [ -d .git ] || [ -f .git ]; then
     version="$version-dirty"
   fi
 else
-  echo "error: cannot get project version." 1>&2
-  exit 1
+  error "cannot get project version, not a git checkout nor a distribution tarball."
 fi
 
 # Use printf to avoid the trailing new line that m4_esyscmd would not handle.
