build: Use two space indentation for shell code

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -179,14 +179,14 @@ update-po:
 dist-hook:
 	echo $(VERSION) >$(distdir)/.dist-version
 	if [ -e .git ]; then \
-		for file in `git ls-files | grep -v .gitignore`; do \
-			if [ ! -e "$(distdir)/$$file" ]; then \
-				echo "$$file is missing in $(distdir)" >&2 ; \
-				exit 1 ; \
-			fi ; \
-		done ; \
-		XDG_CONFIG_HOME= HOME= \
-		git log -C --stat 1.15.0.. >$(distdir)/ChangeLog; \
+	  for file in `git ls-files | grep -v .gitignore`; do \
+	    if [ ! -e "$(distdir)/$$file" ]; then \
+	      echo "$$file is missing in $(distdir)" >&2 ; \
+	      exit 1 ; \
+	    fi ; \
+	  done ; \
+	  XDG_CONFIG_HOME= HOME= \
+	  git log -C --stat 1.15.0.. >$(distdir)/ChangeLog; \
 	fi
 
 clean-local: doc-clean coverage-clean check-clean
diff --git a/dselect/Makefile.am b/dselect/Makefile.am
--- a/dselect/Makefile.am
+++ b/dselect/Makefile.am
@@ -56,11 +56,11 @@ CLEANFILES = curkeys.h
 curkeys.$(OBJEXT): curkeys.h
 curkeys.h: $(srcdir)/keyoverride $(srcdir)/mkcurkeys.pl
 	$(AM_V_GEN) cursesfile=`echo '#include "dselect-curses.h"' | \
-		$(CPP) $(CPPFLAGS) -I$(top_builddir) -I $(srcdir) - | \
-		grep '[^-]curses\.h' | head -n 1 | \
-		sed -e 's/^[^"]*"//; s/".*$$//'`; \
+	  $(CPP) $(CPPFLAGS) -I$(top_builddir) -I $(srcdir) - | \
+	  grep '[^-]curses\.h' | head -n 1 | \
+	  sed -e 's/^[^"]*"//; s/".*$$//'`; \
 	if [ "$$cursesfile" = "" ]; then \
-		echo "can't find curses file"; exit 1; \
+	  echo "can't find curses file"; exit 1; \
 	fi; \
 	$(PERL) $(srcdir)/mkcurkeys.pl $< $$cursesfile >$@
 
