Reformat shell code to follow the coding style

diff --git a/dselect/methods/disk/install b/dselect/methods/disk/install
--- a/dselect/methods/disk/install
+++ b/dselect/methods/disk/install
@@ -24,77 +24,76 @@ cd "$vardir/methods/disk"
 
 xit=1
 trap '
-	if [ -n "$umount" ]
-	then
-		umount "$umount" >/dev/null 2>&1
-	fi
-	exit $xit
+  if [ -n "$umount" ]; then
+    umount "$umount" >/dev/null 2>&1
+  fi
+  exit $xit
 ' 0
 
-if [ -n "$p_blockdev" ]
-then
-	umount="$p_mountpoint"
-	mount -rt "$p_fstype" -o nosuid,nodev "$p_blockdev" "$p_mountpoint"
+if [ -n "$p_blockdev" ]; then
+  umount="$p_mountpoint"
+  mount -rt "$p_fstype" -o nosuid,nodev "$p_blockdev" "$p_mountpoint"
 fi
 
 predep="$vardir/predep-package"
-while true
-do
-	set +e
-	dpkg --admindir "$vardir" --predep-package >"$predep"
-	rc=$?
-	set -e
-	if test $rc = 1; then break; fi
-	test $rc = 0
+while true; do
+  set +e
+  dpkg --admindir "$vardir" --predep-package >"$predep"
+  rc=$?
+  set -e
+  if test $rc = 1; then
+    break
+  fi
+  test $rc = 0
 
-	perl -e '
-		($binaryprefix,$predep) = @ARGV;
-		$binaryprefix =~ s,/*$,/, if length($binaryprefix);
-		open(P, "< $predep") or die "cannot open $predep: $!\n";
-		while (<P>) {
-			s/\s*\n$//;
-			$package= $_ if s/^Package: //i;
-			@filename= split(/ /,$_) if s/^Filename: //i;
-			@msdosfilename= split(/ /,$_) if s/^MSDOS-Filename: //i;
-		}
-		die "internal error - no package" if length($package) == 0;
-		die "internal error - no filename" if not @filename;
-		die "internal error - mismatch >@filename< >@msdosfilename<"
-			if @filename && @msdosfilename &&
-			   @filename != @msdosfilename;
-		@invoke=(); $|=1;
-		for ($i=0; $i<=$#filename; $i++) {
-			$ppart= $i+1;
-			print "Looking for part $ppart of $package ... ";
-			if (-f "$binaryprefix$filename[$i]") {
-				$print= $filename[$i];
-				$invoke= "$binaryprefix$filename[$i]";
-			} elsif (-f "$binaryprefix$msdosfilename[$i]") {
-				$print= $msdosfilename[$i];
-				$invoke= "$binaryprefix$msdosfilename[$i]";
-			} else {
-				$base= $filename[$i]; $base =~ s,.*/,,;
-				$msdosbase= $msdosfilename[$i]; $msdosbase =~ s,.*/,,;
-				$c = open(X, "-|"));
-				if (not defined $c) {
-					die "failed to fork for find: $!\n";
-				}
-				if (!$c) {
-					exec("find", "-L",
-					     length($binaryprefix) ?
-					     $binaryprefix : ".",
-					     "-name",$base,"-o","-name",$msdosbase);
-					die "failed to exec find: $!\n";
-				}
-				while (chop($invoke= <X>)) { last if -f $invoke; }
-				$print= $invoke;
-				if (substr($print,0,length($binaryprefix)+1) eq
-				    "$binaryprefix/") {
-					$print= substr($print,length($binaryprefix));
-				}
+  perl -e '
+	($binaryprefix,$predep) = @ARGV;
+	$binaryprefix =~ s,/*$,/, if length($binaryprefix);
+	open(P, "< $predep") or die "cannot open $predep: $!\n";
+	while (<P>) {
+		s/\s*\n$//;
+		$package= $_ if s/^Package: //i;
+		@filename= split(/ /,$_) if s/^Filename: //i;
+		@msdosfilename= split(/ /,$_) if s/^MSDOS-Filename: //i;
+	}
+	die "internal error - no package" if length($package) == 0;
+	die "internal error - no filename" if not @filename;
+	die "internal error - mismatch >@filename< >@msdosfilename<"
+		if @filename && @msdosfilename &&
+		   @filename != @msdosfilename;
+	@invoke=(); $|=1;
+	for ($i=0; $i<=$#filename; $i++) {
+		$ppart= $i+1;
+		print "Looking for part $ppart of $package ... ";
+		if (-f "$binaryprefix$filename[$i]") {
+			$print= $filename[$i];
+			$invoke= "$binaryprefix$filename[$i]";
+		} elsif (-f "$binaryprefix$msdosfilename[$i]") {
+			$print= $msdosfilename[$i];
+			$invoke= "$binaryprefix$msdosfilename[$i]";
+		} else {
+			$base= $filename[$i]; $base =~ s,.*/,,;
+			$msdosbase= $msdosfilename[$i]; $msdosbase =~ s,.*/,,;
+			$c = open(X, "-|"));
+			if (not defined $c) {
+				die "failed to fork for find: $!\n";
 			}
-			if (!length($invoke)) {
-				warn "
+			if (!$c) {
+				exec("find", "-L",
+				     length($binaryprefix) ?
+				     $binaryprefix : ".",
+				     "-name",$base,"-o","-name",$msdosbase);
+				die "failed to exec find: $!\n";
+			}
+			while (chop($invoke= <X>)) { last if -f $invoke; }
+			$print= $invoke;
+			if (substr($print,0,length($binaryprefix)+1) eq
+			    "$binaryprefix/") {
+				$print= substr($print,length($binaryprefix));
+			}
+		}
+		if (!length($invoke)) {
+			warn "
 
 Cannot find the appropriate file(s) anywhere needed to install or upgrade
 package $package. Expecting version $version or later, as listed in the
@@ -107,23 +106,24 @@ and rerun the installation, or upgrade the package by using
 \"dpkg --install --auto-deconfigure" by hand.
 
 ";
-				exit(1);
-			}
-			print "$print\n";
-			push(@invoke,$invoke);
+			exit(1);
 		}
-		print "Running dpkg -iB for $package ...\n";
-		exec("dpkg","--admindir",$vardir,"-iB","--",@invoke);
-		die "failed to exec dpkg: $!\n";
-	' -- "$p_mountpoint$p_main_binary" "$predep"
+		print "$print\n";
+		push(@invoke,$invoke);
+	}
+	print "Running dpkg -iB for $package ...\n";
+	exec("dpkg","--admindir",$vardir,"-iB","--",@invoke);
+	die "failed to exec dpkg: $!\n";
+  ' -- "$p_mountpoint$p_main_binary" "$predep"
 done
 
-for f in main ctb nf lcl
-do
-	eval 'this_binary=$p_'$f'_binary'
-	if [ -z "$this_binary" ]; then continue; fi
-	echo Running dpkg --admindir $vardir -iGROEB "$p_mountpoint$this_binary"
-	dpkg --admindir $vardir -iGROEB "$p_mountpoint$this_binary"
+for f in main ctb nf lcl; do
+  eval 'this_binary=$p_'$f'_binary'
+  if [ -z "$this_binary" ]; then
+    continue
+  fi
+  echo Running dpkg --admindir $vardir -iGROEB "$p_mountpoint$this_binary"
+  dpkg --admindir $vardir -iGROEB "$p_mountpoint$this_binary"
 done
 
 echo -n 'Installation OK.  Hit RETURN.  '
diff --git a/dselect/methods/multicd/install b/dselect/methods/multicd/install
--- a/dselect/methods/multicd/install
+++ b/dselect/methods/multicd/install
@@ -21,54 +21,50 @@ vardir="$1"
 method=$2
 option=$3
 
-
 cd "$vardir/methods/$method"
 
 . ./shvar.$option
 
-
 #debug() { echo "DEBUG: $@"; }
-debug() { true; }
+debug() {
+  true
+}
 iarch=$(dpkg --print-architecture)
-ismulti() { test -e "$1/.disk/info" || test -e "$1$2/.disk/info"; }
+ismulti() {
+  test -e "$1/.disk/info" || test -e "$1$2/.disk/info"
+}
 
 # 1/ mountpoint
 # 2/ hierarchy
 getdisklabel () {
-    debug "$1" "$2"
-    if [ -f $1/.disk/info ]
-    then
-        echo -n $(head -1 "$1/.disk/info")
-    else
-        if [ -f $1$2/.disk/info ]
-	then
-            echo -n $(head -1 "$1$2/.disk/info")
-	else
-            echo -n 'Non-Debian disc'
-	fi
-    fi
+  debug "$1" "$2"
+  if [ -f $1/.disk/info ]; then
+   echo -n $(head -1 "$1/.disk/info")
+  elif [ -f $1$2/.disk/info ]; then
+    echo -n $(head -1 "$1$2/.disk/info")
+  else
+    echo -n 'Non-Debian disc'
+  fi
 }
 
 xit=1
 
 do_umount() {
-	if [ -n "$umount" ]; then
-		echo umount "$umount"
-		#">/dev/null" "2>&1"
-	fi
+  if [ -n "$umount" ]; then
+    echo umount "$umount"
+    #">/dev/null" "2>&1"
+  fi
 }
 
 do_mount() {
-	if [ ! -b "$p_blockdev" ]
-	then
-		loop=",loop"
-	fi
+  if [ ! -b "$p_blockdev" ]; then
+    loop=",loop"
+  fi
 
-	if [ -n "$p_blockdev" ]
-	then
-		umount="$p_mountpoint"
-		echo mount -rt iso9660 -o nosuid,nodev${loop} "$p_blockdev" "$p_mountpoint"\; umount="$p_mountpoint"
-	fi
+  if [ -n "$p_blockdev" ]; then
+    umount="$p_mountpoint"
+    echo mount -rt iso9660 -o nosuid,nodev${loop} "$p_blockdev" "$p_mountpoint"\; umount="$p_mountpoint"
+  fi
 }
 
 trap 'eval $(do_umount); exit $xit' 0
@@ -76,33 +72,34 @@ trap 'eval $(do_umount); exit $xit' 0
 eval $(do_mount)
 
 predep="$vardir/predep-package"
-while true
-do
-	thisdisk="$(getdisklabel ${p_mountpoint} ${p_hierbase})"
-	set +e
-	dpkg --predep-package >"$predep"
-	rc=$?
-	set -e
-	if test $rc = 1; then break; fi
-	test $rc = 0
+while true; do
+  thisdisk="$(getdisklabel ${p_mountpoint} ${p_hierbase})"
+  set +e
+  dpkg --predep-package >"$predep"
+  rc=$?
+  set -e
+  if test $rc = 1; then
+    break
+  fi
+  test $rc = 0
 
-	perl -e '
-		($binaryprefix,$predep,$thisdisk) = @ARGV;
-		open(P, "< $predep") or die "cannot open $predep: $!\n";
-		while (<P>) {
-			s/\s*\n$//;
-			$package= $_ if s/^Package: //i;
-			/^X-Medium:\s+(.*)\s*/ and $medium = $1;
-			@filename= split(/ /,$_) if s/^Filename: //i;
-			@msdosfilename= split(/ /,$_) if s/^MSDOS-Filename: //i;
-		}
-		die "internal error - no package" if length($package) == 0;
-		die "internal error - no filename" if not @filename;
-		die "internal error - mismatch >@filename< >@msdosfilename<"
-			if @filename && @msdosfilename &&
-			   @filename != @msdosfilename;
-		if ($medium && ($medium ne $thisdisk)) {
-			print "
+  perl -e '
+	($binaryprefix,$predep,$thisdisk) = @ARGV;
+	open(P, "< $predep") or die "cannot open $predep: $!\n";
+	while (<P>) {
+		s/\s*\n$//;
+		$package= $_ if s/^Package: //i;
+		/^X-Medium:\s+(.*)\s*/ and $medium = $1;
+		@filename= split(/ /,$_) if s/^Filename: //i;
+		@msdosfilename= split(/ /,$_) if s/^MSDOS-Filename: //i;
+	}
+	die "internal error - no package" if length($package) == 0;
+	die "internal error - no filename" if not @filename;
+	die "internal error - mismatch >@filename< >@msdosfilename<"
+		if @filename && @msdosfilename &&
+		   @filename != @msdosfilename;
+	if ($medium && ($medium ne $thisdisk)) {
+		print "
 
 This is
     $thisdisk
@@ -111,40 +108,40 @@ However, $package is expected on disc:
 Please change the discs and press <RETURN>.
 
 ";
-			exit(1);
-		}
-		@invoke=(); $|=1;
-		for ($i=0; $i<=$#filename; $i++) {
-			$ppart= $i+1;
-			print "Looking for part $ppart of $package ... ";
-			if (-f "$binaryprefix$filename[$i]") {
-				$print= $filename[$i];
-				$invoke= "$binaryprefix$filename[$i]";
-			} elsif (-f "$binaryprefix$msdosfilename[$i]") {
-				$print= $msdosfilename[$i];
-				$invoke= "$binaryprefix$msdosfilename[$i]";
-			} else {
-				$base= $filename[$i]; $base =~ s,.*/,,;
-				$msdosbase= $msdosfilename[$i]; $msdosbase =~ s,.*/,,;
-				$c = open(X, "-|"));
-				if (not defined $c) {
-					die "failed to fork for find: $!\n";
-				}
-				if (!$c) {
-					exec("find", "-L",
-					     length($binaryprefix) ? $binaryprefix : ".",
-					     "-name",$base,"-o","-name",$msdosbase);
-					die "failed to exec find: $!\n";
-				}
-				while (chop($invoke= <X>)) { last if -f $invoke; }
-				$print= $invoke;
-				if (substr($print,0,length($binaryprefix)+1) eq
-				    "$binaryprefix/") {
-					$print= substr($print,length($binaryprefix));
-				}
+		exit(1);
+	}
+	@invoke=(); $|=1;
+	for ($i=0; $i<=$#filename; $i++) {
+		$ppart= $i+1;
+		print "Looking for part $ppart of $package ... ";
+		if (-f "$binaryprefix$filename[$i]") {
+			$print= $filename[$i];
+			$invoke= "$binaryprefix$filename[$i]";
+		} elsif (-f "$binaryprefix$msdosfilename[$i]") {
+			$print= $msdosfilename[$i];
+			$invoke= "$binaryprefix$msdosfilename[$i]";
+		} else {
+			$base= $filename[$i]; $base =~ s,.*/,,;
+			$msdosbase= $msdosfilename[$i]; $msdosbase =~ s,.*/,,;
+			$c = open(X, "-|"));
+			if (not defined $c) {
+				die "failed to fork for find: $!\n";
 			}
-			if (!length($invoke)) {
-				warn "
+			if (!$c) {
+				exec("find", "-L",
+				     length($binaryprefix) ? $binaryprefix : ".",
+				     "-name",$base,"-o","-name",$msdosbase);
+				die "failed to exec find: $!\n";
+			}
+			while (chop($invoke= <X>)) { last if -f $invoke; }
+			$print= $invoke;
+			if (substr($print,0,length($binaryprefix)+1) eq
+			    "$binaryprefix/") {
+				$print= substr($print,length($binaryprefix));
+			}
+		}
+		if (!length($invoke)) {
+			warn "
 
 Cannot find the appropriate file(s) anywhere needed to install or upgrade
 package $package. Expecting version $version or later, as listed in the
@@ -157,18 +154,18 @@ and rerun the installation, or upgrade the package by using
 \"dpkg --install --auto-deconfigure" by hand.
 
 ";
-				exit(1);
-			}
-			print "$print\n";
-			push(@invoke,$invoke);
+			exit(1);
 		}
-		print "Running dpkg -iB for $package ...\n";
-		exec("dpkg","-iB","--",@invoke);
-		die "failed to exec dpkg: $!\n";
-	' -- "$p_mountpoint$p_hierbase" "$predep" "$thisdisk"
+		print "$print\n";
+		push(@invoke,$invoke);
+	}
+	print "Running dpkg -iB for $package ...\n";
+	exec("dpkg","-iB","--",@invoke);
+	die "failed to exec dpkg: $!\n";
+  ' -- "$p_mountpoint$p_hierbase" "$predep" "$thisdisk"
 done
 
-	perl -e '
+perl -e '
 	$SIG{INT} = sub { cd $vardir; unlink <tmp/*>; exit 1; };
 	$| = 1;
 	my ($vardir, $mountpoint, $hierbase, $mount, $umount) = @ARGV;
@@ -281,7 +278,6 @@ done
 	exit $ouch;
 
 ' "$vardir" "$p_mountpoint" "$p_hierbase" "$(do_mount)" "$(do_umount)"
-
 
 echo -n 'Installation OK.  Hit RETURN.  '
 read response
diff --git a/dselect/methods/multicd/setup b/dselect/methods/multicd/setup
--- a/dselect/methods/multicd/setup
+++ b/dselect/methods/multicd/setup
@@ -31,100 +31,94 @@ dist=stable
 
 xit=1
 trap '
-	rm -f $tp.?
-	if [ -n "$umount" ]
-	then
-		umount "$umount" >/dev/null 2>&1
-	fi
-	exit $xit
+  rm -f $tp.?
+  if [ -n "$umount" ]; then
+    umount "$umount" >/dev/null 2>&1
+  fi
+  exit $xit
 ' 0
 
-if ls -d "$tp.?" >/dev/null 2>&1
-then
-	rm $tp.?
+if ls -d "$tp.?" >/dev/null 2>&1; then
+  rm $tp.?
 fi
 
 #debug() { echo "DEBUG: $@"; }
-debug() { true; }
-ismulti() { debug $1 $2; test -e "$1/.disk/info" || test -e "$1$2/.disk/info"; }
+debug() {
+  true
+}
+ismulti() {
+  debug $1 $2; test -e "$1/.disk/info" || test -e "$1$2/.disk/info"
+}
 
 # 1/ mountpoint
 # 2/ hierarchy
 getdisklabel () {
-    debug "$1" "$2"
-    if [ -f $1/.disk/info ]
-    then
-        echo -n $(head -1 "$1/.disk/info")
-    else
-        if [ -f $1$2/.disk/info ]
-	then
-            echo -n $(head -1 "$1$2/.disk/info")
-	else
-            echo -n 'Non-Debian disc'
-	fi
-    fi
+  debug "$1" "$2"
+  if [ -f $1/.disk/info ]; then
+    echo -n $(head -1 "$1/.disk/info")
+  elif [ -f $1$2/.disk/info ]; then
+    echo -n $(head -1 "$1$2/.disk/info")
+  else
+    echo -n 'Non-Debian disc'
+  fi
 }
 
 yesno () {
-	while true
-	do
-		echo -n "$2 [$1]  "
-		read response
-		if [ -z "$response" ]
-		then
-			response="$1"
-		fi
-		case "$response" in
-		[Nn]*)	yesno=no ; return ;;
-		[Yy]*)	yesno=yes ; return ;;
-		esac
-	done
+  while true; do
+    echo -n "$2 [$1]  "
+    read response
+    if [ -z "$response" ]; then
+      response="$1"
+    fi
+    case "$response" in
+    [Nn]*)
+      yesno=no
+      return
+      ;;
+    [Yy]*)
+      yesno=yes
+      return
+      ;;
+    esac
+  done
 }
 
 getblockdev () {
-	mountpoint="$vardir/methods/mnt"
-	if [ -z "$defaultdevice" ]
-	then
-		defaultdevice="$newdefaultdevice"
-	elif [ "$defaultdevice" != "$newdefaultdevice" ]
-	then
-		echo \
-	"Last time you specified installation from $defaultdevice."
-	fi
-	promptstring="$1"
-	while [ -z "$blockdevice" ]
-	do
-		echo -n "$promptstring [$defaultdevice]:  "
-		read response
-		if [ -z "$response" ]
-		then
-			response="$defaultdevice"
-		fi
-		if [ ! -b "$response" ]
-		then
-			echo "$response is not a block device - will try as loopback.";
-			loop=",loop"
-		fi
-		tryblockdevice="$response"
-		if [ $option = multi_cd ]
-		then
-			fstype=iso9660
-		fi
-		umount="$mountpoint"
-		if mount -rt "$fstype" -o nosuid,nodev$loop "$tryblockdevice" "$mountpoint"
-		then
-			echo
-			blockdevice="$tryblockdevice"
-		else
-			umount=""
-			echo \
-	"Unable to mount $tryblockdevice on $mountpoint, type $fstype."
-		fi
-	done
+  mountpoint="$vardir/methods/mnt"
+  if [ -z "$defaultdevice" ]; then
+    defaultdevice="$newdefaultdevice"
+  elif [ "$defaultdevice" != "$newdefaultdevice" ]; then
+    echo "Last time you specified installation from $defaultdevice."
+  fi
+  promptstring="$1"
+  while [ -z "$blockdevice" ]; do
+    echo -n "$promptstring [$defaultdevice]:  "
+    read response
+    if [ -z "$response" ]; then
+      response="$defaultdevice"
+    fi
+    if [ ! -b "$response" ]; then
+      echo "$response is not a block device - will try as loopback."
+      loop=",loop"
+    fi
+    tryblockdevice="$response"
+    if [ $option = multi_cd ]; then
+      fstype=iso9660
+    fi
+    umount="$mountpoint"
+    if mount -rt "$fstype" -o nosuid,nodev$loop "$tryblockdevice" "$mountpoint"
+    then
+      echo
+      blockdevice="$tryblockdevice"
+    else
+      umount=""
+      echo "Unable to mount $tryblockdevice on $mountpoint, type $fstype."
+    fi
+  done
 }
 
 outputparam () {
-	echo "$2" | sed -e "s/'/'\\\\''/; s/^/$1='/; s/$/'/" >&3
+  echo "$2" | sed -e "s/'/'\\\\''/; s/^/$1='/; s/$/'/" >&3
 }
 
 ## MAIN
@@ -151,117 +145,97 @@ If you make a mistake, use the interrupt key ($intrkey) to abort.
 #   The default block device to mount.
 
 p_usedevel=no
-if [ -f shvar.$option ]
-then
-	. ./shvar.$option
-	defaultdevice="$p_blockdev"
-	usedevel="$p_usedevel"
+if [ -f shvar.$option ]; then
+  . ./shvar.$option
+  defaultdevice="$p_blockdev"
+  usedevel="$p_usedevel"
 fi
 
-if [ $option = multi_cd ]
-then
-	mount >$tp.m
-	sed -n 's/ ([^)]*)$//; s/^[^ ]* on //; s/ type iso9660$//p' <$tp.m >$tp.l
-	ncdroms=$(wc -l <$tp.l)
-	if [ $ncdroms -gt 1 ]
-	then
-		response=""
-		while [ -z "$response" ]
-		do
-			echo \
-	'Several CD-ROMs (or other ISO9660 filesystems) are mounted:'
-			egrep 'type iso9660 \([^)]*\)$' <$tp.m | nl
-			echo -n \
-	"Is it any of these ?  Type a number, or 'n' for none.  "
-			read response
-                        response="$(echo \"$response\" | sed -e 's/[ 	]*$//')"
-			if expr "$response" : '[0-9][0-9]*$' >/dev/null && \
-			   [ $response -ge 1 -a $response -le $ncdroms ]
-			then
-                                mountpoint="$(sed -n $response'p' <$tp.l)"
-				echo
-			elif expr "$response" : '[Nn]' >/dev/null
-			then
-				mountpoint=""
-			else
-				response=""
-			fi
-		done
-	elif [ $ncdroms = 1 ]
-	then
-		mountpoint="$(cat $tp.l)"
-		perl -ne 'print if s/ type iso9660 \([^)]*\)$// && s/ on .*$//;' \
-			<$tp.m >$tp.d
-		blockdevice="$(cat $tp.d)"
-		yesno yes \
-	"Found a CD-ROM: $blockdevice, mounted on $mountpoint. Is it the right one?"
-		if [ $yesno = no ]
-		then
-			echo 'Unmounting it ...'
-			umount="$mountpoint"
-			while true
-			do
-				echo -n \
-	'Please insert the right disc, and hit return:  '
-				read response
-				if mount -rt iso9660 -o nosuid,nodev \
-					"$blockdevice" "$mountpoint"
-				then
-					echo
-					break
-				fi
-			done
-		fi
-	fi
-	if [ -z "$mountpoint" ]
-	then
-		if [ -b /dev/cdrom ]
-		then
-			echo \
-	'Found that /dev/cdrom exists and is a block device.'
-			newdefaultdevice=/dev/cdrom
-		fi
-		getblockdev 'Insert the CD-ROM and enter the block device name'
-	fi
+if [ $option = multi_cd ]; then
+  mount >$tp.m
+  sed -n 's/ ([^)]*)$//; s/^[^ ]* on //; s/ type iso9660$//p' <$tp.m >$tp.l
+  ncdroms=$(wc -l <$tp.l)
+  if [ $ncdroms -gt 1 ]; then
+    response=""
+    while [ -z "$response" ]; do
+      echo 'Several CD-ROMs (or other ISO9660 filesystems) are mounted:'
+      egrep 'type iso9660 \([^)]*\)$' <$tp.m | nl
+      echo -n "Is it any of these ?  Type a number, or 'n' for none.  "
+      read response
+      response="$(echo \"$response\" | sed -e 's/[ 	]*$//')"
+      if expr "$response" : '[0-9][0-9]*$' >/dev/null && \
+         [ $response -ge 1 -a $response -le $ncdroms ]; then
+               mountpoint="$(sed -n $response'p' <$tp.l)"
+        echo
+      elif expr "$response" : '[Nn]' >/dev/null; then
+        mountpoint=""
+      else
+        response=""
+      fi
+    done
+  elif [ $ncdroms = 1 ]; then
+    mountpoint="$(cat $tp.l)"
+    perl -ne 'print if s/ type iso9660 \([^)]*\)$// && s/ on .*$//;' \
+      <$tp.m >$tp.d
+    blockdevice="$(cat $tp.d)"
+    yesno yes \
+      "Found a CD-ROM: $blockdevice, mounted on $mountpoint. Is it the right one?"
+    if [ $yesno = no ]; then
+      echo 'Unmounting it ...'
+      umount="$mountpoint"
+      while true; do
+        echo -n 'Please insert the right disc, and hit return:  '
+        read response
+        if mount -rt iso9660 -o nosuid,nodev \
+           "$blockdevice" "$mountpoint"; then
+          echo
+          break
+        fi
+      done
+    fi
+  fi
+  if [ -z "$mountpoint" ]; then
+    if [ -b /dev/cdrom ]; then
+      echo 'Found that /dev/cdrom exists and is a block device.'
+      newdefaultdevice=/dev/cdrom
+    fi
+    getblockdev 'Insert the CD-ROM and enter the block device name'
+  fi
 fi
 
-if [ -n "$mountpoint" ]
-then
-	# We must have $mountpoint
-	if [ $option = multi_cd ]
-	then
-		echo \
+if [ -n "$mountpoint" ]; then
+  # We must have $mountpoint
+  if [ $option = multi_cd ]; then
+    echo \
 'All directory names should be entered relative to the root of the CD-ROM.
 '
-	else
-		echo \
+  else
+    echo \
 "All directory names should be entered relative to the root of the
 $fstype filesystem on $blockdevice.
 "
-	fi
+  fi
 fi
 
 # now try to get the users idea where the debian
 # hierarchy start below the mointpoint
 
 debug "mountpoint: $mountpoint"
-while true
-do
-	if ismulti "${mountpoint}" "${hierbase}"; then
-		multi=yes
-	fi
+while true; do
+  if ismulti "${mountpoint}" "${hierbase}"; then
+    multi=yes
+  fi
 
-	if [ $option = multi_cd ]
-	then
-		echo \
+  if [ $option = multi_cd ]; then
+    echo \
 "Need to know where on the CD-ROM the top level of the Debian
 distribution is - this will usually contain the 'dists' directory.
 
 If the CD-ROM is badly organized and doesn't have a straightforward copy of
 the distribution you may answer 'none' and the needed parts will be prompted
 individually."
-	else
-		echo \
+  else
+    echo \
 "In order to make it easy to find the relevant files, it is preferred
 to install from a straightforward copy of the Debian distribution.
 To use this, it is required to know where the top level of that copy of the
@@ -269,197 +243,189 @@ distribution is - this directory usually contains the Packages-Master file.
 
 If you do not have a straightforward copy of the distribution available
 just answer 'none' and the needed parts will be prompted individually."
-	fi
+  fi
 
-	defhierbase=none
-	if [ -n "$p_hierbase" ]; then
-		if [ -d "$mountpoint/$p_hierbase/dists/$dist/main/binary-$iarch" \
-			-o -n "$multi" ]; then
-			echo "Last time you said '$p_hierbase', and that looks plausible."
-			defhierbase="$p_hierbase"
-		else
-			echo "
+  defhierbase=none
+  if [ -n "$p_hierbase" ]; then
+    if [ -d "$mountpoint/$p_hierbase/dists/$dist/main/binary-$iarch" \
+         -o -n "$multi" ]; then
+      echo "Last time you said '$p_hierbase', and that looks plausible."
+      defhierbase="$p_hierbase"
+    else
+      echo "
 Last time you said '$p_hierbase', but that doesn't look plausible,
 since '$p_hierbase/dists/$dist/main/binary-$iarch' doesn't seem to exist.
 And it does not appear that you're using a multi-CD set."
-		fi
-	fi
+    fi
+  fi
 
-	# at this point defhierbase is set if it looks plausible
-	# if ‘none’ was entered, we assume a CD with a debian/ directory
+  # at this point defhierbase is set if it looks plausible
+  # if ‘none’ was entered, we assume a CD with a debian/ directory
 
-	if [ none = "$defhierbase" -a -d "$mountpoint/debian/dists/$dist/main/binary-$iarch" ]
-	then
-		echo "'/debian' exists and looks plausible, so that's the default."
-		defhierbase=/debian
-	fi
+  if [ none = "$defhierbase" -a -d "$mountpoint/debian/dists/$dist/main/binary-$iarch" ]
+  then
+    echo "'/debian' exists and looks plausible, so that's the default."
+    defhierbase=/debian
+  fi
 
-	echo -n "Distribution top level ? [$defhierbase]  "
-	read response
-	if [ -z "$response" ]; then response="$defhierbase"; fi
-	if [ none = "$response" ]; then
-		hierbase=""
-		break
-	elif ismulti "$mountpoint" "$response" && [ -z "$multi" ]; then
-		multi=yes
-	fi
+  echo -n "Distribution top level ? [$defhierbase]  "
+  read response
+  if [ -z "$response" ]; then
+    response="$defhierbase"
+  fi
+  if [ none = "$response" ]; then
+    hierbase=""
+    break
+  elif ismulti "$mountpoint" "$response" && [ -z "$multi" ]; then
+    multi=yes
+  fi
 
-	if ! [ -d "$mountpoint/$response/dists/$dist/main/binary-$iarch" \
-			-o -n "$multi" ]; then
-		echo \
+  if ! [ -d "$mountpoint/$response/dists/$dist/main/binary-$iarch" \
+         -o -n "$multi" ]; then
+    echo \
 "Neither $response/dists/$dist/main/binary-$iarch does not exist,
 nor are you using a multi-CD set"
-		break
-	fi
+    break
+  fi
 
-	hierbase="$(echo \"$response\" | sed -e 's:/$::; s:^/*:/:; s:/\+:/:g;')"
-	debug "hierbase: [$hierbase]"
+  hierbase="$(echo \"$response\" | sed -e 's:/$::; s:^/*:/:; s:/\+:/:g;')"
+  debug "hierbase: [$hierbase]"
 
-	if [ -n "$multi" ]; then
-		disklabel=$(getdisklabel "$mountpoint" "/$response")
-		echo "Ok, this is disc"
-		echo "    $disklabel"
-		#echo "Updating multi CD contents file cache ..."
-		#multi_contentsfile="${mountpoint}/${response}/.disk/contents.gz"
-		#zcat "$multi_contentsfile" > disk-contents.$option
-	fi
+  if [ -n "$multi" ]; then
+    disklabel=$(getdisklabel "$mountpoint" "/$response")
+    echo "Ok, this is disc"
+    echo "    $disklabel"
+    #echo "Updating multi CD contents file cache ..."
+    #multi_contentsfile="${mountpoint}/${response}/.disk/contents.gz"
+    #zcat "$multi_contentsfile" > disk-contents.$option
+  fi
 
-	break;
+  break;
 done
 
 distribution=$dist
-if [ -n "$hierbase" ]
-then
-	if [ -d "$mountpoint/$hierbase/dists/unstable/binary-$iarch" ]
-	then
-		echo \
+if [ -n "$hierbase" ]; then
+  if [ -d "$mountpoint/$hierbase/dists/unstable/binary-$iarch" ]; then
+    echo \
 '
 Both a stable released distribution and a work-in-progress
 development tree are available for installation.  Would you like to
 use the unreleased development tree (this is only recommended for
 experts who like to live dangerously and want to help with testing) ?'
-		yesno "$p_usedevel" 'Use unreleased development distribution ?'
-		usedevel="$yesno"
-		if [ "$usedevel" = yes ]
-		then
-			distribution=development
-		fi
-	else
-		usedevel=no
-	fi
-	echo
+    yesno "$p_usedevel" 'Use unreleased development distribution ?'
+    usedevel="$yesno"
+    if [ "$usedevel" = yes ]; then
+      distribution=development
+    fi
+  else
+    usedevel=no
+  fi
+  echo
 fi
 
 case "$hierbase" in
-/* )	;;
-'' )	;;
-* )	hierbase="/$hierbase" ;;
+/* )
+  ;;
+'' )
+  ;;
+* )
+  hierbase="/$hierbase"
+  ;;
 esac
 
 check_binary () {
-	# args: area-in-messages directory
-	debug "check_binary($@)"
+  # args: area-in-messages directory
+  debug "check_binary($@)"
 
-	if [ ! -d "${mountpoint}$2" -a -z "$multi" ]
-	then
-		echo "'$2' does not exist."
-		return
-	fi
+  if [ ! -d "${mountpoint}$2" -a -z "$multi" ]; then
+    echo "'$2' does not exist."
+    return
+  fi
 
 # In this special case it is ok for a sub-distribution to not contain any
 # .deb files.  Each CD should contain all Packages.cd files but doesn't
 # need to contain the .deb files.
 #
-#  	if ! { find -L "$mountpoint$2" -name '*.deb' -print \
-#  		| head -1 | grep . ; } >/dev/null 2>&1 && [ -z "$multi" ];
-#  	then
-#  		echo "'$2' does not contain any *.deb packages."
-#  		return
-#  	fi
+#   if ! { find -L "$mountpoint$2" -name '*.deb' -print \
+#     | head -1 | grep . ; } >/dev/null 2>&1 && [ -z "$multi" ];
+#   then
+#     echo "'$2' does not contain any *.deb packages."
+#     return
+#   fi
 
-	this_binary="$2"
-	echo -n "Using '$this_binary' as $1 binary directory"
+  this_binary="$2"
+  echo -n "Using '$this_binary' as $1 binary directory"
 
-	if [ -n "$multi" ]; then
-		this_disk=$(getdisklabel ${mountpoint} "/$hierbase")
-		echo " from disc"
-		echo "    '$this_disk'"
-	else
-		echo ""
-	fi
+  if [ -n "$multi" ]; then
+    this_disk=$(getdisklabel ${mountpoint} "/$hierbase")
+    echo " from disc"
+    echo "    '$this_disk'"
+  else
+    echo ""
+  fi
 }
 
 find_area () {
-	# args: area-in-messages area-in-vars subdirectory-in-hier
-	#       last-time-binary last-time-packages
-	debug "find_area($@)"
-	this_binary=''
-	this_packages=''
-	this_disk=''
-	if [ -n "$hierbase" ]
-	then
-		check_binary $1 $(echo "$hierbase/dists/$3/$1/binary-$iarch" | sed 's:/\+:/:g')
-		debug "THIS_BINARY $this_binary"
-	fi
-	if [ $option = multi_cd -a $2 = nf -a -z "$this_binary" ]
-	then
-		echo "
+  # args: area-in-messages area-in-vars subdirectory-in-hier
+  #       last-time-binary last-time-packages
+  debug "find_area($@)"
+  this_binary=''
+  this_packages=''
+  this_disk=''
+  if [ -n "$hierbase" ]; then
+    check_binary $1 $(echo "$hierbase/dists/$3/$1/binary-$iarch" | sed 's:/\+:/:g')
+    debug "THIS_BINARY $this_binary"
+  fi
+  if [ $option = multi_cd -a $2 = nf -a -z "$this_binary" ]; then
+    echo "
 Note: most CD-ROM distributions of Debian do not include programs
 available in the 'non-free' directory of the distribution site.
 This is because these programs have copyrights that prevent
 distribution for profit on a CD-ROM - ie they are not free software.
 If you wish to install these programs you'll have to get them from an
 alternative source."
-	fi
-	while [ -z "$this_binary" ]
-	do
-		defaultbinary="$4"
-		echo "
+  fi
+  while [ -z "$this_binary" ]; do
+    defaultbinary="$4"
+    echo "
 Which directory contains the *.deb packages from the $1 distribution
 area (this directory is named '$3/binary' on the distribution site) ?
 Say 'none' if this area is not available."
-		if [ $2 != main -a -z "$defaultbinary" ]
-		then
-			defaultbinary=none
-		fi
-		echo -n \
+    if [ $2 != main -a -z "$defaultbinary" ]; then
+      defaultbinary=none
+    fi
+    echo -n \
 "Enter _$1_ binary directory. [$4]
  ?  "
-		read response
-		if [ -z "$response" -a -n "$defaultbinary" ]
-		then
-			response="$defaultbinary"
-		fi
-		if [ none = "$response" ]
-		then
-			break
-		fi
-		case "$response" in
-		'' | none)	continue		;;
-		esac
-		check_binary $1 "$(echo \"$response\" | sed -e 's:/$::; s:^/*:/:')"
-	done
-	if [ -n "$this_binary" ]
-	then
-		if [ "$multi" = "yes" ]; then
-			for f in Packages.cd.gz packages.cd.gz Packages.cd packages.cd
-			do
-				if [ -f "$mountpoint/$this_binary/$f" ]
-				then
-					this_packages="$this_binary/$f"
-					echo "Using '$this_packages' for $1."
-					break
-				fi
-			done
-		else
-			if [ -f "${mountpoint}${hierbase}/.disk/packages/$1/Packages.gz" ]; then
-				this_packages=$(echo "${hierbase}/.disk/packages/$1/Packages.gz"|sed 's:/\+:/:g')
-				echo "Using '${this_packages}' for $1."
-			fi
-		fi
-		while [ -z "$this_packages" ]
-		do
-			echo -n "
+    read response
+    if [ -z "$response" -a -n "$defaultbinary" ]; then
+      response="$defaultbinary"
+    fi
+    if [ none = "$response" ]; then
+      break
+    fi
+    case "$response" in
+    '' | none)
+      continue
+      ;;
+    esac
+    check_binary $1 "$(echo \"$response\" | sed -e 's:/$::; s:^/*:/:')"
+  done
+  if [ -n "$this_binary" ]; then
+    if [ "$multi" = "yes" ]; then
+      for f in Packages.cd.gz packages.cd.gz Packages.cd packages.cd; do
+        if [ -f "$mountpoint/$this_binary/$f" ]; then
+          this_packages="$this_binary/$f"
+          echo "Using '$this_packages' for $1."
+          break
+        fi
+      done
+    elif [ -f "${mountpoint}${hierbase}/.disk/packages/$1/Packages.gz" ]; then
+      this_packages=$(echo "${hierbase}/.disk/packages/$1/Packages.gz"|sed 's:/\+:/:g')
+      echo "Using '${this_packages}' for $1."
+    fi
+    while [ -z "$this_packages" ]; do
+      echo -n "
 Cannot find the $1 'Packages.cd' file. The information in the
 'Packages.cd' file is important for package selection during new
 installations, and is very useful for upgrades.
@@ -477,23 +443,32 @@ you wish to install.
 Where is the _$1_ 'Packages.cd' file (if none is available, say 'none')
 [$5]
  ?  "
-			read response
-			if [ -z "$response" -a -n "$5" ]
-			then
-				response="$5"
-			fi
-			case "$response" in
-			'')		break				;;
-			none)		break				;;
-			scan)		this_packages=scan		;;
-			/*)		this_packages="$response"	;;
-			*)		this_packages="/$response"	;;
-			esac
-		done
-	fi
-	eval $2'_binary="$this_binary"'
-	eval $2'_packages="$this_packages"'
-	eval $2'_disk="$this_disk"'
+      read response
+      if [ -z "$response" -a -n "$5" ]; then
+        response="$5"
+      fi
+      case "$response" in
+      '')
+        break
+        ;;
+      none)
+        break
+        ;;
+      scan)
+        this_packages=scan
+        ;;
+      /*)
+        this_packages="$response"
+        ;;
+      *)
+        this_packages="/$response"
+        ;;
+      esac
+    done
+  fi
+  eval $2'_binary="$this_binary"'
+  eval $2'_packages="$this_packages"'
+  eval $2'_disk="$this_disk"'
 }
 
 find_area main main "$distribution" "$p_main_binary" "$p_main_packages"
