perl: Add POD to all private modules
Mark them explicitly as private modules, add some minimal description
for their purpose. This also fixes the warnings from pod2man where it
cannot generate a man page for these.

Closes: #1030660

diff --git a/scripts/Makefile.am b/scripts/Makefile.am
--- a/scripts/Makefile.am
+++ b/scripts/Makefile.am
@@ -176,8 +176,10 @@ if BUILD_POD_DOC
 	  $(POD2MAN) $(POD2MAN_OPTS) --center=libdpkg-perl \
 	    --name="$$name" --section=$(man_perl_section) $(srcdir)/$$module \
 	    >$(DESTDIR)$(man3dir)/$$name.$(man_perl_section); \
-	  test -s $(DESTDIR)$(man3dir)/$$name.$(man_perl_section) || \
-	  rm -f $(DESTDIR)$(man3dir)/$$name.$(man_perl_section); \
+	  if ! [ -s "$(DESTDIR)$(man3dir)/$$name.$(man_perl_section)" ]; then \
+	    echo "error: empty $(man3dir)/$$name.$(man_perl_section)" 2>&1; \
+	    exit 1; \
+	  fi; \
 	done
 endif
 
